const pedidos = [
{
    "id": 61565,
    "fecha": "14/10/2020",
    "contactoRemitente": "ALEJANDRA RUBIO",
    "empresaRemitente": "ALEJANDRA RUBIO",
    "direccionRemitente": "EDUARDO ASTETE MENDOZA 280",
    "distritoRemitente": "Santiago de Surco",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "KARLA FARFÁN",
    "empresaConsignado": "",
    "direccionConsignado": "UNIDAD VECINAL DE MATUTE CHALET 20A",
    "telefonoConsignado": 946847625,
    "otroDatoConsignado": "REFERENCIAS 1: ALTURA DE LA CDRA 5 DE LA AVENIDA MÉXICO REFERENCIA 2: ENTRE LAS AVENIDAS PALERMO Y ANDAHUAYLAS REFERENCIA 3: FRENTE AL BANCO INTERBANK",
    "tarifa": 7,
    "tarifaSugerida": 14,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 8.5,
    "CO2Ahorrado": 2.6,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "LA VICTORIA",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "LUIS ALEJANDRO CHACON",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 61374,
    "fecha": "12/10/2020",
    "contactoRemitente": "MARYTHE PASAPERA",
    "empresaRemitente": "HOME STORE",
    "direccionRemitente": "AV LOS PATRIOTAS 320 DPTO 101",
    "distritoRemitente": "San Miguel",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": 986277482,
    "contactoConsignado": "YESENIA QUISPE RAMÍREZ",
    "empresaConsignado": "",
    "direccionConsignado": "JIRÓN DELFÍN PUCCIO ULLOA MANZANA W LOTE 13 URBANIZACIÓN SAN TADEO",
    "telefonoConsignado": 966305638,
    "otroDatoConsignado": "REFERENCIA: FRENTE A LA ESCUELA TÉCNICA DEL EJÉRCITO O A LA ALTURA DEL TOTTUS DE HUAYLAS",
    "tarifa": 7,
    "tarifaSugerida": 24,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.9,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 15.8,
    "CO2Ahorrado": 4.7,
    "ruido": 0.4,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "CHORRILLOS",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "EDUARDO CARBAJAL",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 60277,
    "fecha": "03/10/2020",
    "contactoRemitente": "MARYTHE PASAPERA",
    "empresaRemitente": "MARYTHE PASAPERA",
    "direccionRemitente": "AV LOS PATRIOTAS 320",
    "distritoRemitente": "San Miguel",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": 986277482,
    "contactoConsignado": "MARIELA HUAPAYA",
    "empresaConsignado": "",
    "direccionConsignado": "AV FRANCISCO DE ZELA 1563 DPTO 402",
    "telefonoConsignado": "999-393-177",
    "otroDatoConsignado": "A MEDIA CUADRA DE LA SUNARP QUE ESTÁ AL FRENTE DEL HOSPITAL REBAGLIATI",
    "tarifa": 7,
    "tarifaSugerida": 12,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 7,
    "CO2Ahorrado": 2.1,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "LINCE",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "GREG DURAND",
    "operador": "szegarra",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 60260,
    "fecha": "03/10/2020",
    "contactoRemitente": "GABRIELA MONZON",
    "empresaRemitente": "PLAN CONSIENTE SHOP",
    "direccionRemitente": "CESAR DIAZ 143",
    "distritoRemitente": "Santiago de Surco",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "NADIA ORBEGOSO VERASTEGUI",
    "empresaConsignado": "",
    "direccionConsignado": "MELITON RODRÍGUEZ 153 DPTO 301,",
    "telefonoConsignado": 943403978,
    "otroDatoConsignado": "EM APPS DE MAPAS USUALMENTE SALE SOLO COMO RODRÍGUEZ 153",
    "tarifa": 7,
    "tarifaSugerida": 19,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "Crédito 7 Días",
    "distancia": 12.1,
    "CO2Ahorrado": 3.6,
    "ruido": 0.3,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "SAN MIGUEL",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "MOISES CABRERA",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 60102,
    "fecha": "02/10/2020",
    "contactoRemitente": "PAULA HERRERA",
    "empresaRemitente": "PEQUEÑA TRIBU",
    "direccionRemitente": "CALLE MANCO CÁPAC 880",
    "distritoRemitente": "Miraflores",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "SARA ERIKA TELLEZ HINOJOSA",
    "empresaConsignado": "",
    "direccionConsignado": "VELASCO ASTETE 2176 DEP 201.",
    "telefonoConsignado": 956092883,
    "otroDatoConsignado": "REFERENCIA: ESTÁ A LA ALTURA DE AV BENAVIDES CON VELASCO ASTETE, AL COSTADO DEL STARBUCKS",
    "tarifa": 7,
    "tarifaSugerida": 9,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 4.7,
    "CO2Ahorrado": 1.4,
    "ruido": 0.1,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Santiago de Surco",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "Daniel Colmenares",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 59741,
    "fecha": "29/09/2020",
    "contactoRemitente": "KATHERINE  VALDEZ",
    "empresaRemitente": "KATHERINE VALDEZ",
    "direccionRemitente": "CALLE ALFA LEÓN 140 DPTO 405",
    "distritoRemitente": "Surquillo",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": 945051117,
    "contactoConsignado": "MILAGROS CARMELINO",
    "empresaConsignado": "",
    "direccionConsignado": "CIRCUNVALACIÓN DEL GOLF LOS INCAS 543",
    "telefonoConsignado": "994 055721",
    "otroDatoConsignado": "REF LA MISMA CALLE QUE EL CLUB GOLF LOS INCAS - CERCA ÓVALO DE LA FONTANA",
    "tarifa": 7,
    "tarifaSugerida": 13,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 8,
    "CO2Ahorrado": 2.4,
    "ruido": 0.2,
    "rolCliente": "DESTINATARIO",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Cercado de Lima",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "JONEL ALEGRE",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 59670,
    "fecha": "29/09/2020",
    "contactoRemitente": "ANTONINI",
    "empresaRemitente": "CLIENTE ÚNICO",
    "direccionRemitente": "CALLE SAN ANTONIO 253",
    "distritoRemitente": "Barranco",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": 969949902,
    "contactoConsignado": "ERIKA DOMINGUEZ",
    "empresaConsignado": "",
    "direccionConsignado": "CALLE ZEUS MANZANA A28 LOTE 35 URBANIZACIÓN SAGITARIO SEGUNDO PISO",
    "telefonoConsignado": 993452866,
    "otroDatoConsignado": "REFERENCIA LOS CONDOMINIOS DEL PARQUE DE SURCO O A 5 CUADRAS APROXIMADAMENTE DE LA COMISARÍA DE SAGITARIO",
    "tarifa": 7,
    "tarifaSugerida": 10,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 5.9,
    "CO2Ahorrado": 1.8,
    "ruido": 0.1,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Santiago de Surco",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "Persona",
    "status": 4,
    "mobiker": "DIEGO SALAZAR",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 59546,
    "fecha": "28/09/2020",
    "contactoRemitente": "CECILIA CECILIA DELGADO",
    "empresaRemitente": "CECILIA DELGADO",
    "direccionRemitente": "PROLONGACIÓN CUSCO 1025.",
    "distritoRemitente": "San Miguel",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": 995039748,
    "contactoConsignado": "CONSUELO LEQUERICA",
    "empresaConsignado": "",
    "direccionConsignado": "JIRÓN MARIANO MELGAR 184, 4TO PISO URBANIZACIÓN LOS PRÓCERES",
    "telefonoConsignado": "Sin teléfono",
    "otroDatoConsignado": "RECOGER ENTRE 4 - 6:30PM / REFERENCIA: JIRÓN FRANCISCO JAVIER MARIÁTEGUI 901",
    "tarifa": 7,
    "tarifaSugerida": 7,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 13.3,
    "CO2Ahorrado": 4,
    "ruido": 0.3,
    "rolCliente": "DESTINATARIO",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Santiago de Surco",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "GREG DURAND",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 59339,
    "fecha": "26/09/2020",
    "contactoRemitente": "DIANA GONZÁLEZ",
    "empresaRemitente": "DIANA GONZÁLEZ",
    "direccionRemitente": "AV ARBOLEDA 467 DPTO 201.",
    "distritoRemitente": "La Molina",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "MARÍA LUISA",
    "empresaConsignado": "",
    "direccionConsignado": "AV LOS ANDES MANZANA F1 LOTE 12",
    "telefonoConsignado": "Sin teléfono",
    "otroDatoConsignado": "URBANIZACIÓN LOS HUERTOS SOL DE LA MOLINA ENTRAR POR LA CALLE LA PUNTA JUNTO AL GRIFO REPSOL FRENTE AL CASINO DE POLICÍA",
    "tarifa": 13,
    "tarifaSugerida": 13,
    "recaudo": 0,
    "tramite": 0,
    "comision": 7.8,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 7.6,
    "CO2Ahorrado": 2.3,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "LA MOLINA",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "JAVIER RODRIGUEZ",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 58298,
    "fecha": "18/09/2020",
    "contactoRemitente": "DIANA GONZÁLEZ",
    "empresaRemitente": "DIANA GONZÁLEZ",
    "direccionRemitente": "AV ARBOLEDA 467 DPTO 201.",
    "distritoRemitente": "La Molina",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "MARÍA LUISA UGARTE",
    "empresaConsignado": "",
    "direccionConsignado": "AV LOS ANDES MANZANA F1 LOTE 12 URBANIZACIÓN LOS HUERTOS SOL DE LA MOLINA",
    "telefonoConsignado": 986776111,
    "otroDatoConsignado": "REF  ENTRAR POR LA CALLE LA PUNTA JUNTO AL GRIFO REPSOL FRENTE AL CASINO DE POLICÍA",
    "tarifa": 13,
    "tarifaSugerida": 13,
    "recaudo": 0,
    "tramite": 0,
    "comision": 7.8,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 7.6,
    "CO2Ahorrado": 2.3,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "LA MOLINA",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "MOISES CABRERA",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 57193,
    "fecha": "09/09/2020",
    "contactoRemitente": "ANYELA VALENCIA",
    "empresaRemitente": "EL HORNO DE DO",
    "direccionRemitente": "JR CUZCO 429 DEPARTAMENTO 801",
    "distritoRemitente": "Magdalena del Mar",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "ALESSANDRA GÜÍMAC ROJAS",
    "empresaConsignado": "",
    "direccionConsignado": "CALLE JOSÉ NEYRA,MZ E1 LOT 2,",
    "telefonoConsignado": 943825964,
    "otroDatoConsignado": "EN EL NIDO VIRGEN DE LA PAZ, A UNA CUADRA DE ANGAMOS CON AVIACIÓN",
    "tarifa": 7,
    "tarifaSugerida": 14,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "Crédito 7 Días",
    "distancia": 8.9,
    "CO2Ahorrado": 2.7,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Santiago de Surco",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "EDGARDO HUANUCO",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 56955,
    "fecha": "07/09/2020",
    "contactoRemitente": "GABRIELA MONZON",
    "empresaRemitente": "PLAN CONSIENTE SHOP",
    "direccionRemitente": "CESAR DIAZ 143",
    "distritoRemitente": "Santiago de Surco",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "JOEL",
    "empresaConsignado": "",
    "direccionConsignado": "AV MARIATEGUI 850",
    "telefonoConsignado": 917657363,
    "otroDatoConsignado": "MUNICIPALIDAD DE JESÚS MARÍA",
    "tarifa": 7,
    "tarifaSugerida": 17,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "EFECTIVO EN ORIGEN",
    "distancia": 10.6,
    "CO2Ahorrado": 3.2,
    "ruido": 0.3,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Jesús María",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "RONALD SALAZAR",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 56587,
    "fecha": "04/09/2020",
    "contactoRemitente": "ANA SOFIA  CASTILLO JIMENEZ",
    "empresaRemitente": "ANA SOFIA CASTILLO JIMENEZ",
    "direccionRemitente": "CALLE 19 153 CORPAC",
    "distritoRemitente": "San Isidro",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "KELLY RACHEL",
    "empresaConsignado": "",
    "direccionConsignado": "CALLE ARICA 655 DEPARTAMENTO 204",
    "telefonoConsignado": 997517535,
    "otroDatoConsignado": "REF A DOS CUADRAS DEL OVALO GUTIÉRREZ Y MEDIA CUADRA DE ANGAMOS OESTE Y UNA CUADRA DE COMANDANTE ESPINAR",
    "tarifa": 7,
    "tarifaSugerida": 7,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 3.7,
    "CO2Ahorrado": 1.1,
    "ruido": 0.1,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Miraflores",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "MIA ROSAS",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 56189,
    "fecha": "01/09/2020",
    "contactoRemitente": "DIEGO BAXERIAS",
    "empresaRemitente": "DIEGO BAXERIAS",
    "direccionRemitente": "JIRÓN MONTE CAOBA 1015 DPTO. G-401",
    "distritoRemitente": "Santiago de Surco",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "ELIZABETH ZULOAGA",
    "empresaConsignado": "",
    "direccionConsignado": "CALLE JULIO C. TELLO 128",
    "telefonoConsignado": 975954624,
    "otroDatoConsignado": "DEBEN INGRESAR POR LA REJA QUE ESTÁ A LA ALT DE LA CDRA. 1 DE LA AV. PRECURSORES. *LLAMAR ANTES DE LLEGAR*",
    "tarifa": 7,
    "tarifaSugerida": 24,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 15.9,
    "CO2Ahorrado": 4.8,
    "ruido": 0.4,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "SAN MIGUEL",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "CRISTIAN TUEROS",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 55903,
    "fecha": "29/08/2020",
    "contactoRemitente": "LESLIE KAM",
    "empresaRemitente": "LESLIE KAM",
    "direccionRemitente": "AVENIDA CLUB GOLF LOS INCAS 66B",
    "distritoRemitente": "Santiago de Surco",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "956470783, (LLAMAR CUANDO LLEGUEN POR FAVOR, PORQUE MI TIMBRE ESTÁ MALOGRADO )",
    "contactoConsignado": "NICOLLE RAMIREZ",
    "empresaConsignado": "",
    "direccionConsignado": "CALLE PADRE URRACA 140 TORRE 9 DPTO 803",
    "telefonoConsignado": 938383260,
    "otroDatoConsignado": "CONDOMINIOS PARQUES DE LA HUACA ETAPA 7, A LA ALTURA DE BRITÁNICO DE AV LA MARINA",
    "tarifa": 7,
    "tarifaSugerida": 25,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 16.5,
    "CO2Ahorrado": 5,
    "ruido": 0.4,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "SAN MIGUEL",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "EDGAR NAVARRO",
    "operador": "szegarra",
    "viajes": 1,
    "facturado": "SI",
    "compensado": "SI"
  },
{
    "id": 54951,
    "fecha": "21/08/2020",
    "contactoRemitente": "MIRIAM SCHWARZ",
    "empresaRemitente": "INSTITUTO DE PROTOCOLO Y EVENTOS SAC",
    "direccionRemitente": "MARISCAL LA MAR 398 OFICINA 402",
    "distritoRemitente": "Miraflores",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "*RECOGER A PARTIR DE LAS 2PM*",
    "contactoConsignado": "",
    "empresaConsignado": "",
    "direccionConsignado": "JR. BELLO HORIZONTE 2450 - 2A",
    "telefonoConsignado": "Sin teléfono",
    "otroDatoConsignado": "ALT. CDRA 24 DE LA AV. PERÚ",
    "tarifa": 19,
    "tarifaSugerida": 19,
    "recaudo": 0,
    "tramite": 0,
    "comision": 11.4,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 12,
    "CO2Ahorrado": 3.6,
    "ruido": 0.3,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "San Martín de Porres",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "DIOBER CARREÑO",
    "operador": "szegarra",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 54528,
    "fecha": "18/08/2020",
    "contactoRemitente": "KARLA .",
    "empresaRemitente": "ECOBAG COMPANY",
    "direccionRemitente": "AVENIDA SERGIO BERNALES 236 DPTO 1502- BARRIO MÉDICO",
    "distritoRemitente": "Surquillo",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "ADRIANA GODINEZ SEMINO",
    "empresaConsignado": "",
    "direccionConsignado": "CALLE MARGARITA LOTE 26, MZ C6.",
    "telefonoConsignado": 954792594,
    "otroDatoConsignado": "LO UBICAS COMO: MARGARITA 181 (REFERENCIA: CASA CON PORTÓN DE MADERA JUNTO A UNA BODEGA, ESQUINA DE JR. CABO BLANCO CON CALLE MARGARITA )",
    "tarifa": 12,
    "tarifaSugerida": 16,
    "recaudo": 0,
    "tramite": 0,
    "comision": 7.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 10.3,
    "CO2Ahorrado": 3.1,
    "ruido": 0.3,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "CHORRILLOS",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "ILEN MOYA HERNANDEZ",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 54072,
    "fecha": "14/08/2020",
    "contactoRemitente": "VERONICA  VELARDE",
    "empresaRemitente": "VERONICA VELARDE",
    "direccionRemitente": "CALLE PEDRO VENTURO 330",
    "distritoRemitente": "Miraflores",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": 925835015,
    "contactoConsignado": "HELLEN OLIVA",
    "empresaConsignado": "",
    "direccionConsignado": "CALLE LAS VIOLETAS 202, DPTO 503, URB LINDA VISTA",
    "telefonoConsignado": 969632370,
    "otroDatoConsignado": "REF A 5 CUADRAS DE PLAZA VEA DE CIRCUNVALACIÓN",
    "tarifa": 7,
    "tarifaSugerida": 11,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 6.5,
    "CO2Ahorrado": 2,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "ATE",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "Joan Dávila",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "SI",
    "compensado": "SI"
  },
{
    "id": 54026,
    "fecha": "14/08/2020",
    "contactoRemitente": "ALEXANDRA PALOMINO",
    "empresaRemitente": "ALEXANDRA PALOMINO",
    "direccionRemitente": "CALLE LOS ROBLES 2615",
    "distritoRemitente": "San Isidro",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "ESTHER TRUJILLO SÁNCHEZ",
    "empresaConsignado": "",
    "direccionConsignado": "CALLE ARTURO TOSCANINI 150 / DPTO 403",
    "telefonoConsignado": 989669519,
    "otroDatoConsignado": "(REFERENCIA A UNA CUADRA DE LA MUNICIPALIDAD DE SAN BORJA, ENTRAR POR LA ALTURA DEL CLUB LORETO POR LA AVENIDA JOAQUÍN MADRID.",
    "tarifa": 14,
    "tarifaSugerida": 14,
    "recaudo": 0,
    "tramite": 0,
    "comision": 8.4,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 7.5,
    "CO2Ahorrado": 2.3,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "San Borja",
    "modalidad": "Una Vía",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "MIA ROSAS",
    "operador": "avallejo",
    "viajes": 2,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 53790,
    "fecha": "12/08/2020",
    "contactoRemitente": "PILAR  ESTEVES",
    "empresaRemitente": "PILAR ESTEVES",
    "direccionRemitente": "AV CIRCUNVALACION GOLF LOS INCAS 510/530 TORRE A DPTO S-101",
    "distritoRemitente": "Santiago de Surco",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "*RECOGER POR LA MAÑANA*",
    "contactoConsignado": "MEYLLY",
    "empresaConsignado": "",
    "direccionConsignado": ":CALLE LAS GAVIOTAS 2110  ES UN CONDOMINIO PARQUES DE SURCO 3",
    "telefonoConsignado": "997 089 874",
    "otroDatoConsignado": "POR FAVOR ESPERAR QUE ME HAGA EL PAGO ANTES DE ENTREGAR LOS 3 PAQUETES  GRACIAS",
    "tarifa": 14,
    "tarifaSugerida": 14,
    "recaudo": 0,
    "tramite": 0,
    "comision": 8.4,
    "tipoCarga": "Documento/Sobre",
    "formaPago": "TRANSFERENCIA",
    "distancia": 7.5,
    "CO2Ahorrado": 2.3,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Santiago de Surco",
    "modalidad": "Una Vía",
    "tipoDeEnvio": "PERSONA",
    "status": 4,
    "mobiker": "Joan Dávila",
    "operador": "avallejo",
    "viajes": 2,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 53775,
    "fecha": "12/08/2020",
    "contactoRemitente": "VANESSA QUIÑONES",
    "empresaRemitente": "VANESSA QUIÑONES",
    "direccionRemitente": "AVENIDA PRIMAVERA 1981 DPT 203",
    "distritoRemitente": "Santiago de Surco",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "EYLIN",
    "empresaConsignado": "",
    "direccionConsignado": "JR. ICA 999 INT 3",
    "telefonoConsignado": "Sin teléfono",
    "otroDatoConsignado": "ALT DE LA IGLESIA NTRA SEÑORA DE MONSERRAT.",
    "tarifa": 9,
    "tarifaSugerida": 29,
    "recaudo": 0,
    "tramite": 0,
    "comision": 5.4,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 19.8,
    "CO2Ahorrado": 5.9,
    "ruido": 0.5,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Cercado de Lima",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "JAVIER MEJIAS",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 53249,
    "fecha": "05/08/2020",
    "contactoRemitente": "NELLY HERRERA",
    "empresaRemitente": "CLIENTE ÚNICO",
    "direccionRemitente": "AV. BRASIL 2481",
    "distritoRemitente": "Jesús María",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "992641899 *RECOGER ENTRE 12.30 Y 4PM*",
    "contactoConsignado": "CLAUDIA FARFÁN",
    "empresaConsignado": "",
    "direccionConsignado": "CALLE ATAHUALPA 210",
    "telefonoConsignado": 984713740,
    "otroDatoConsignado": "ESTÁ A DOS CUADRAS DEL PARQUE KENNEDY",
    "tarifa": 7,
    "tarifaSugerida": 11,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 6.3,
    "CO2Ahorrado": 1.9,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Miraflores",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "ALEX TAPULLIMA",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 53219,
    "fecha": "07/08/2020",
    "contactoRemitente": "CLAUDIA BRAVO",
    "empresaRemitente": "CLAUDIA BRAVO",
    "direccionRemitente": "AV. MARGINAL 145",
    "distritoRemitente": "Ate",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "EDITH MOLINA MIRANDA",
    "empresaConsignado": "",
    "direccionConsignado": "CALLE BOLÍVAR 388 DPTO 303",
    "telefonoConsignado": 984378802,
    "otroDatoConsignado": "REFERENCIA:ALTURA DE CUADRA 6 DE BENAVIDES EDIFICIO CATALUÑA COLOR MARRON EN UNA ESQUINA.",
    "tarifa": 7,
    "tarifaSugerida": 14,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 8.5,
    "CO2Ahorrado": 2.5,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Miraflores",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "MANUEL VEGA",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 52742,
    "fecha": "04/08/2020",
    "contactoRemitente": "ALEXANDRA PALOMINO",
    "empresaRemitente": "ALEXANDRA PALOMINO",
    "direccionRemitente": "CALLE LOS ROBLES 2615",
    "distritoRemitente": "San Isidro",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "PIA IPARRAGUIRRE",
    "empresaConsignado": "",
    "direccionConsignado": "ALMIRANTE LORD NELSON 149",
    "telefonoConsignado": 969872677,
    "otroDatoConsignado": "*LLAMAR XQ TIMBRE ESTÁ MALOGRADO.*",
    "tarifa": 7,
    "tarifaSugerida": 7,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 2.8,
    "CO2Ahorrado": 0.8,
    "ruido": 0.1,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Miraflores",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "EVELIN LOPEZ",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 52682,
    "fecha": "03/08/2020",
    "contactoRemitente": "CAMILA MUÑOZ",
    "empresaRemitente": "CLIENTE ÚNICO",
    "direccionRemitente": "JR SANTA ELENA SUR 180 DPT 401",
    "distritoRemitente": "Santiago de Surco",
    "telefonoRemitente": "959135006",
    "otroDatoRemitente": "ALT 18 PRIMAVERA",
    "contactoConsignado": "FIORELLA RODRIGUEZ",
    "empresaConsignado": "",
    "direccionConsignado": "JIRÓN MARTÍN ALONSO DE MEZA #265 DPT 301",
    "telefonoConsignado": "Sin teléfono",
    "otroDatoConsignado": "ESTÁ A TRES CUADRAS DE PLAZA SAN MIGUEL",
    "tarifa": 7,
    "tarifaSugerida": 7,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 14.3,
    "CO2Ahorrado": 4.3,
    "ruido": 0.4,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "SAN MIGUEL",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "RICARDO RUIZ",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 52644,
    "fecha": "03/08/2020",
    "contactoRemitente": "ANDREA CONTRERAS",
    "empresaRemitente": "ANDREA CONTRERAS",
    "direccionRemitente": "JOSE CORZO 102 DPTO 201",
    "distritoRemitente": "Santiago de Surco",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "ALICIA CABRERA VALENTÍN",
    "empresaConsignado": "",
    "direccionConsignado": "JR RESTAURACIÓN 487  ALTURA RAMBLA BRASIL",
    "telefonoConsignado": "945 522 270",
    "otroDatoConsignado": "REF  ALTURA RAMBLA BRASIL / UN FAVOR CUANDO LO ENVÍEN DILE QUE NO TOQUE EL TIMBRE DE LA CASA PLS  QUE LA LLAMEN Y ELLA BAJA",
    "tarifa": 7,
    "tarifaSugerida": 7,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 3.8,
    "CO2Ahorrado": 1.1,
    "ruido": 0.1,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Breña",
    "modalidad": "Una Vía",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "BORIS FERRER",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 52262,
    "fecha": "30/07/2020",
    "contactoRemitente": "MARIANA ZUÑIGA",
    "empresaRemitente": "ECOLMENA SAC",
    "direccionRemitente": "MIGUEL ALJOVIN 221 DPTO 201-",
    "distritoRemitente": "Miraflores",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "FABIOLA HUAYTAN",
    "empresaConsignado": "",
    "direccionConsignado": "CALLE LOS PERALES 292-DPTO 202",
    "telefonoConsignado": 961774718,
    "otroDatoConsignado": "REFERENCIA ALTURA DE LA CUADRO 14 DE LA AV JORGE CHÁVEZ",
    "tarifa": 7,
    "tarifaSugerida": 7,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "Crédito 7 Días",
    "distancia": 3.6,
    "CO2Ahorrado": 1.1,
    "ruido": 0.1,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Santiago de Surco",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "YOSEL SULBARAN",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 51865,
    "fecha": "27/07/2020",
    "contactoRemitente": "ALEXANDRA PALOMINO",
    "empresaRemitente": "ALEXANDRA PALOMINO",
    "direccionRemitente": "CALLE LOS ROBLES 2615",
    "distritoRemitente": "San Isidro",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "MARÍA FERNANDA HURTADO",
    "empresaConsignado": "",
    "direccionConsignado": "PJ. SAN MARTÍN 175.",
    "telefonoConsignado": 985214489,
    "otroDatoConsignado": "ALTURA DE LA CUADRA 8 DE LA CALLE SAN MARTÍN",
    "tarifa": 7,
    "tarifaSugerida": 10,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 5.5,
    "CO2Ahorrado": 1.6,
    "ruido": 0.1,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Miraflores",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "DAVID CARRERO",
    "operador": "FCARBAJAL",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 51145,
    "fecha": "21/07/2020",
    "contactoRemitente": "CLAUDIA BRAVO",
    "empresaRemitente": "CLAUDIA BRAVO",
    "direccionRemitente": "AV. MARGINAL 145",
    "distritoRemitente": "Ate",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "NELLY GABRIELA COLOMA BAUTISTA",
    "empresaConsignado": "",
    "direccionConsignado": "CALLE MANUEL RAYGADA MZ E LT 13",
    "telefonoConsignado": 943536970,
    "otroDatoConsignado": "CASA BLANCA DE 3 PISOS CON REJAS NEGRAS. ESTA UBICADO A MITAD DE CUADRA (ENTRE LA ENTRADA DE LA CALLE Y UN PARQUE) 2DA ENTRADA DE MATELLINI REF: ESTACIÓN MATELLINI DEL METROPOLITANO",
    "tarifa": 7,
    "tarifaSugerida": 21,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 14.2,
    "CO2Ahorrado": 4.3,
    "ruido": 0.4,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "CHORRILLOS",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "ALEJANDRO MEDINA",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 50949,
    "fecha": "20/07/2020",
    "contactoRemitente": "RENATA TAVARA",
    "empresaRemitente": "PLANTASY",
    "direccionRemitente": "JR. LAS UVAS 390, TORRE 4 DPTO 605",
    "distritoRemitente": "Santiago de Surco",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "GISELLE MIYOSHI",
    "empresaConsignado": "",
    "direccionConsignado": "MADRESELVA 385 DEPA 401, CASUARINAS BAJA",
    "telefonoConsignado": 954146747,
    "otroDatoConsignado": "REF CUADRA 4 DE AV JACARANDÁ,",
    "tarifa": 7,
    "tarifaSugerida": 10,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 5.4,
    "CO2Ahorrado": 1.6,
    "ruido": 0.1,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Santiago de Surco",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "JAVIER ROBAYO",
    "operador": "FCARBAJAL",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 50377,
    "fecha": "15/07/2020",
    "contactoRemitente": "MILDZY MUJICA",
    "empresaRemitente": "CUENTA CONMIGO CUENTOS PERSONALIZADOS",
    "direccionRemitente": "AVENIDA FRANKLIN ROOSEVELT 362",
    "distritoRemitente": "Cercado de Lima",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "LIDIA HUMALA",
    "empresaConsignado": "",
    "direccionConsignado": "JIRÓN EL CASCAJAL 126",
    "telefonoConsignado": "947 396 354",
    "otroDatoConsignado": "CASA CREMA DE 2 PISOS CON PORTÓN DE MADERA",
    "tarifa": 7,
    "tarifaSugerida": 19,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 12.1,
    "CO2Ahorrado": 3.6,
    "ruido": 0.3,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Santiago de Surco",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "EDGAR NAVARRO",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "SI",
    "compensado": "SI"
  },
{
    "id": 50189,
    "fecha": "13/07/2020",
    "contactoRemitente": "ANDREA CONTRERAS",
    "empresaRemitente": "ANDREA CONTRERAS",
    "direccionRemitente": "JOSE CORZO 102 DPTO 201",
    "distritoRemitente": "Santiago de Surco",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "JENNY LEON",
    "empresaConsignado": "",
    "direccionConsignado": "CALLE CANARIOS 103 DPTO 308",
    "telefonoConsignado": 923378933,
    "otroDatoConsignado": "REFERENCIA A  UNA CUADRA Y MEDIA DE LA ESTACIÓN ARAMBURU CON VÍA EXPRESA  EDIFICIO BEIGE CON MARRÓN",
    "tarifa": 14,
    "tarifaSugerida": 14,
    "recaudo": 0,
    "tramite": 0,
    "comision": 8.4,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 7.5,
    "CO2Ahorrado": 2.3,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "SURQUILLO",
    "modalidad": "Una Vía",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "DANNY HUAMAN",
    "operador": "avallejo",
    "viajes": 2,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 49838,
    "fecha": "09/07/2020",
    "contactoRemitente": "CLAUDIA EGUSGUIZA",
    "empresaRemitente": "MORGANA JOYERIAS",
    "direccionRemitente": "JOSE GONZALES 260",
    "distritoRemitente": "Miraflores",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "DIANA MARTINEZ VASQUEZ",
    "empresaConsignado": "",
    "direccionConsignado": "CALLE LOS SAUCOS 329 SALAMANCA",
    "telefonoConsignado": 944429158,
    "otroDatoConsignado": "ESPALDA DEL PLAZA VEA DE CIRCUNVALACIÓN, POR EL TRÉBOL DE JAVIER PRADO",
    "tarifa": 7,
    "tarifaSugerida": 15,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 9.2,
    "CO2Ahorrado": 2.8,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Ate",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "JUAN CARLOS LAURA",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 48885,
    "fecha": "01/07/2020",
    "contactoRemitente": "PAOLA  CHIRINOS",
    "empresaRemitente": "PCH PAOLA CHIRINOS",
    "direccionRemitente": "JR. BATALLÓN TARMA 180 DPTO 503 A",
    "distritoRemitente": "Santiago de Surco",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "CRISTINA BENITEZ",
    "empresaConsignado": "",
    "direccionConsignado": "ALOMIA ROBLES 250. CONDOMINIO EL PRADO, URB. ÁLAMOS DE MONTERRICO",
    "telefonoConsignado": 991831766,
    "otroDatoConsignado": "REF. 2 CDRAS ANTES DE CENTRUM CATÓLICA) SURCO \nLA RECEPCIÓN SERÁ EN LA PUERTA DEL CONDOMINIO, NO ESTÁ PERMITIDO EL INGRESO. PERSONA DEBE AVISAR CUANDO YA SE ENCUENTRE EN LA PUERTA PARA SALIR A RECEPCIONAR",
    "tarifa": 7,
    "tarifaSugerida": 8,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.9,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "EFECTIVO EN ORIGEN",
    "distancia": 4.4,
    "CO2Ahorrado": 1.3,
    "ruido": 0.1,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Santiago de Surco",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "EDUARDO CARBAJAL",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "SI",
    "compensado": "SI"
  },
{
    "id": 48812,
    "fecha": "01/07/2020",
    "contactoRemitente": "DIANDRA  ZEGARRA",
    "empresaRemitente": "DIANDRA ZEGARRA",
    "direccionRemitente": "JR. MANCO SEGUNDO 2202 DPTO 301",
    "distritoRemitente": "Lince",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "ROCIO TORREBLANCA",
    "empresaConsignado": "",
    "direccionConsignado": "LOS JAZMINE 164 DPTO 402",
    "telefonoConsignado": "Sin teléfono",
    "otroDatoConsignado": "ALT CDRA 8 JACARANDA, ATRÁS DE PLAZA VEA DE VALLE HERMOSO",
    "tarifa": 7,
    "tarifaSugerida": 14,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 8.5,
    "CO2Ahorrado": 2.6,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Santiago de Surco",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "DEBORAH CANALES",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "SI",
    "compensado": "SI"
  },
{
    "id": 48579,
    "fecha": "29/06/2020",
    "contactoRemitente": "PATRICIA GUERRERO",
    "empresaRemitente": "FUNNY MARKET",
    "direccionRemitente": "CALLE DELUCCHI 101 1B",
    "distritoRemitente": "Barranco",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "RECOGER PEDIDO PATRICIA GUERRERO",
    "empresaConsignado": "",
    "direccionConsignado": "ALCANFORES 199, TIENDA 103",
    "telefonoConsignado": "Sin teléfono",
    "otroDatoConsignado": "A DOS CUADRAS DEL PARQUE KENNEDY, LOS DÍAS LUNES SÓLO DE 11AM A 3PM SON 2 FUNKOS (DE LA PELÍCULA EL DIABLO VISTE A LA MODA) FRAGIL",
    "tarifa": 7,
    "tarifaSugerida": 7,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "Crédito 7 Días",
    "distancia": 2.2,
    "CO2Ahorrado": 0.7,
    "ruido": 0.1,
    "rolCliente": "DESTINATARIO",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Miraflores",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "ELLIOTH LAURA",
    "operador": "szegarra",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 47432,
    "fecha": "18/06/2020",
    "contactoRemitente": "PILAR CORNEJO",
    "empresaRemitente": "DANKA",
    "direccionRemitente": "PSJ LOS NARDOS 143",
    "distritoRemitente": "San Miguel",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "NELLY REYES",
    "empresaConsignado": "",
    "direccionConsignado": "PASAJE LOS OLIVOS 165",
    "telefonoConsignado": 933035309,
    "otroDatoConsignado": "A 1 CUADRA DE LA CLÍNICA CENTENARIO",
    "tarifa": 7,
    "tarifaSugerida": 20,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 13.4,
    "CO2Ahorrado": 4,
    "ruido": 0.3,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "PUEBLO LIBRE",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "Jorge Dorantes",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 46936,
    "fecha": "15/06/2020",
    "contactoRemitente": "DIANDRA  ZEGARRA",
    "empresaRemitente": "DIANDRA ZEGARRA",
    "direccionRemitente": "JR. MANCO SEGUNDO 2202 DPTO 301",
    "distritoRemitente": "Lince",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "FRANCIS NEUMMAN",
    "empresaConsignado": "",
    "direccionConsignado": "LAS ARACENAS 350 DPTO 101",
    "telefonoConsignado": "Sin teléfono",
    "otroDatoConsignado": "ALTURA PRIMERA CUADRA PEDRO VENTURO, AVIACION CON VILLARÁN",
    "tarifa": 7,
    "tarifaSugerida": 16,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "TRANSFERENCIA",
    "distancia": 9.9,
    "CO2Ahorrado": 3,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Santiago de Surco",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "KENRY LOYOLA",
    "operador": "szegarra",
    "viajes": 1,
    "facturado": "SI",
    "compensado": "SI"
  },
{
    "id": 46719,
    "fecha": "12/06/2020",
    "contactoRemitente": "XIMENA OBLITAS",
    "empresaRemitente": "XIMENA OBLITAS",
    "direccionRemitente": "CALLE MIGUEL CERVELLI 140",
    "distritoRemitente": "La Victoria",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "ALEJANDRA PALZA",
    "empresaConsignado": "",
    "direccionConsignado": "AV. EL SAUCE 527",
    "telefonoConsignado": "989 649 691 Comentarios: Llamar al teléfono cuando lleguen porque la dirección no tiene timbre.",
    "otroDatoConsignado": "REFERENCIA: CERCA AL CRUCE DE AV. AVIACIÓN CON VILLARÁN)",
    "tarifa": 7,
    "tarifaSugerida": 9,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "Crédito 7 Días",
    "distancia": 5,
    "CO2Ahorrado": 1.5,
    "ruido": 0.1,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "SURQUILLO",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "CARLOS ABDALA",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 45811,
    "fecha": "04/06/2020",
    "contactoRemitente": "KEN NOBARU",
    "empresaRemitente": "CASA PIZARRO SAC",
    "direccionRemitente": "DOMINGO ELIAS 160 DPTO J",
    "distritoRemitente": "Miraflores",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "964 645 109",
    "contactoConsignado": "KARINA ROSA SAL Y ROSAS",
    "empresaConsignado": "",
    "direccionConsignado": "CRUCETA 2DA ETAPA BLOCK 43 DPTO 201",
    "telefonoConsignado": "Sin teléfono",
    "otroDatoConsignado": "ES ENTRE LA CUADRA 7 Y 8 DE LA AV. PRÓCERES. EL DELIVERY ES EN LA MISMA CUENTA DEL BCP",
    "tarifa": 7,
    "tarifaSugerida": 13,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Producto E-commerce",
    "formaPago": "Crédito 7 Días",
    "distancia": 7.9,
    "CO2Ahorrado": 2.4,
    "ruido": 0.2,
    "rolCliente": "REMITENTE",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "Santiago de Surco",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "E-COMMERCE",
    "status": 4,
    "mobiker": "CARLOS ABDALA",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
{
    "id": 44161,
    "fecha": "21/05/2020",
    "contactoRemitente": "ANA SOFIA CASTILLO JIRMENEZ",
    "empresaRemitente": "ANA SOFIA",
    "direccionRemitente": "CALLE 19 153 CORPAC",
    "distritoRemitente": "San Isidro",
    "telefonoRemitente": "Sin teléfono",
    "otroDatoRemitente": "",
    "contactoConsignado": "",
    "empresaConsignado": "",
    "direccionConsignado": "AV. SAN BORJA NORTE 548",
    "telefonoConsignado": 992399314,
    "otroDatoConsignado": "REF: A MEDIA CUADRA DE LA AV. AVIACIÓN (ENTRE LA CDA. 26 Y 27). ES UNA RECTA DE CASAS BLANCAS CON REJAS NEGRAS TODAS IGUALES. AL FRENTE EN LA ESQUINA ESTÁ EL GRIFO PECSA",
    "tarifa": 7,
    "tarifaSugerida": 7,
    "recaudo": 0,
    "tramite": 0,
    "comision": 4.2,
    "tipoCarga": "Documento/Sobre",
    "formaPago": "TRANSFERENCIA",
    "distancia": 1.6,
    "CO2Ahorrado": 0.5,
    "ruido": 0,
    "rolCliente": "DESTINATARIO",
    "comentario": "Migración del Sistema",
    "distritoConsignado": "San Borja",
    "modalidad": "UNA VÍA",
    "tipoDeEnvio": "PERSONA",
    "status": 4,
    "mobiker": "LEONARD SANCHEZ",
    "operador": "avallejo",
    "viajes": 1,
    "facturado": "NO",
    "compensado": "NO"
  },
]

module.exports = pedidos;
